<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>RWKVSharp.Core</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>AnyCPU</Platforms>

		<AssemblyName>RWKVSharp.Core</AssemblyName>
		<RootNamespace>RWKVSharp.Core</RootNamespace>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>xcssa</Authors>
		<Company>SSA</Company>
		<Description>implementation of a custom llm model abstract factory pattern</Description>
		<PackageTags>rwkv,rwkv.cpp</PackageTags>
		<PackageProjectUrl>https://github.com/imxcstar/RWKVSharp</PackageProjectUrl>
		<PackageId>$(AssemblyName)</PackageId>
		<Version>$(NUGET_VERSION)</Version>
	</PropertyGroup>
	
</Project>
