<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>RWKVSharp</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Platforms>AnyCPU</Platforms>

		<AssemblyName>RWKVSharp</AssemblyName>
		<RootNamespace>RWKVSharp</RootNamespace>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>xcssa</Authors>
		<Company>SSA</Company>
		<Description>
			rwkv.cpp ggml wrapper for rwkv llm model (cpu)
			Supports Windows/Linux/macOS. Prebuilt binaries included for Windows.
			Other systems need to compile from https://github.com/RWKV/rwkv.cpp
		</Description>
		<PackageProjectUrl>https://github.com/imxcstar/RWKVSharp</PackageProjectUrl>
		<PackageId>$(AssemblyName)</PackageId>
		<Version>$(NUGET_VERSION)</Version>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\RWKVSharp.Core\RWKVSharp.Core.csproj" />
	</ItemGroup>
	
</Project>