<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>RWKVSharp</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Platforms>AnyCPU</Platforms>

		<AssemblyName>RWKVSharp</AssemblyName>
		<RootNamespace>RWKVSharp</RootNamespace>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>xcssa</Authors>
		<Company>SSA</Company>
		<Description>rwkv.cpp wrapper for rwkv llm model. supports windows/linux/macOS.</Description>
		<PackageTags>rwkv,rwkv.cpp</PackageTags>
		<PackageProjectUrl>https://github.com/imxcstar/RWKVSharp</PackageProjectUrl>
		<PackageId>$(AssemblyName)</PackageId>
		<Version>$(NUGET_VERSION)</Version>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\RWKVSharp.Core\RWKVSharp.Core.csproj" />
	</ItemGroup>
	
</Project>