name: Build and Publish .NET Native Packages

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create new release'
        required: true
        type: boolean
      build_native_library:
        description: 'Build Native Library'
        required: true
        type: boolean
  push:
    branches: [main]

env:
  NUGET_VERSION: 1.0.${{ github.run_number }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  NUGET_API_TOKEN: ${{ secrets.RWKVSHARP_NUGET_KEY }}

jobs:
  submodule-check:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 2

      - name: Check submodules
        id: check
        run: |
          current_hash=$(git ls-tree HEAD "libs/rwkv.cpp" 2>/dev/null | awk '{print $3}')
          previous_hash=$(git ls-tree HEAD^ "libs/rwkv.cpp" 2>/dev/null | awk '{print $3}')
          if [ "$current_hash" = "$previous_hash" ]; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Debug output
        run: echo "${{ steps.check.outputs.changed }}"
        
  build_native:
    needs: submodule-check
    if: ${{ needs.submodule-check.outputs.updated == 'true' || github.event.inputs.build_native_library == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # CPU Targets
          - package_id: RWKVSharp.Native.Cpu.avx.win-x64
            os: windows-2019
            arch: x64
            args: -DRWKV_AVX2=OFF
            rid: win-x64
            mode: avx
            type: cpu

          - package_id: RWKVSharp.Native.Cpu.avx2.win-x64
            os: windows-2019
            arch: x64
            rid: win-x64
            mode: avx2
            type: cpu

          - package_id: RWKVSharp.Native.Cpu.avx512.win-x64
            os: windows-2019
            arch: x64
            args: -DRWKV_AVX512=ON
            rid: win-x64
            mode: avx512
            type: cpu

          - package_id: RWKVSharp.Native.Cpu.avx.linux-x64
            os: ubuntu-latest
            arch: x64
            args: -DRWKV_AVX2=OFF
            rid: linux-x64
            mode: avx
            type: cpu

          - package_id: RWKVSharp.Native.Cpu.avx2.linux-x64
            os: ubuntu-latest
            arch: x64
            rid: linux-x64
            mode: avx2
            type: cpu

          - package_id: RWKVSharp.Native.Cpu.avx512.linux-x64
            os: ubuntu-latest
            arch: x64
            args: -DRWKV_AVX512=ON
            rid: linux-x64
            mode: avx512
            type: cpu

          - package_id: RWKVSharp.Native.Cpu.linux-arm64
            os: ubuntu-latest
            arch: arm64
            rid: linux-arm64
            type: cpu

          # cuBLAS Targets
          - package_id: RWKVSharp.Native.cuBLAS.cuda11.3.win-x64
            os: windows-2019
            arch: x64
            args: -DRWKV_CUBLAS=ON
            rid: win-x64
            cuda: 11.3.0

          - package_id: RWKVSharp.Native.cuBLAS.cuda12.8.win-x64
            os: windows-2019
            arch: x64
            args: -DRWKV_CUBLAS=ON
            rid: win-x64
            cuda: 12.8.0

          # Metal Targets
          - package_id: RWKVSharp.Native.Metal.osx-x64
            os: macOS-latest
            arch: x64
            args: -DRWKV_METAL=ON
            rid: osx-x64

          - package_id: RWKVSharp.Native.Metal.osx-arm64
            os: macOS-latest
            arch: arm64
            args: -DRWKV_METAL=ON
            rid: osx-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup CUDA
        if: matrix.cuda
        uses: Jimver/cuda-toolkit@v0.2.21
        with:
          cuda: ${{ matrix.cuda }}
          method: local

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ../libs/rwkv.cpp ${{ matrix.args }} -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cd build
          cmake --build . --config Release --parallel

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Prepare package structure (CPU) (Windows)
        if: matrix.type == 'cpu' && matrix.arch != 'arm64' && runner.os == 'Windows'
        run: |
          $modeDir = "package/runtimes/${{ matrix.rid }}/native/${{ matrix.mode }}"
          New-Item -Path $modeDir -ItemType Directory -Force
          Copy-Item build/bin/Release/rwkv.dll -Destination $modeDir

      - name: Prepare package structure (CPU-arm64 or Other) (Windows)
        if: (matrix.type != 'cpu' || matrix.arch == 'arm64') && runner.os == 'Windows'
        run: |
          $nativeDir = "package/runtimes/${{ matrix.rid }}/native"
          New-Item -Path $nativeDir -ItemType Directory -Force
          Copy-Item build/bin/Release/rwkv.dll -Destination $nativeDir

      - name: Create .nupkg (Windows)
        if: runner.os == 'Windows'
        run: |
          dotnet new classlib -n ${{ matrix.package_id }} -o ./${{ matrix.package_id }} --force
          Set-Location -Path "./${{ matrix.package_id }}"
          Remove-Item "Class1.cs" -Force
          $projectFileContent = @"
          <Project Sdk="Microsoft.NET.Sdk">
            <PropertyGroup>
              <TargetFramework>netstandard2.0</TargetFramework>
              <PackageId>${{ matrix.package_id }}</PackageId>
              <Version>${{ env.NUGET_VERSION }}</Version>
              <Authors>xcssa</Authors>
              <PackageTags>rwkv,rwkv.cpp,native</PackageTags>
              <IncludeBuildOutput>false</IncludeBuildOutput>
            </PropertyGroup>
            <ItemGroup>
              <None Include="../package/runtimes/**" 
                    Pack="true" 
                    PackagePath="runtimes/" />
            </ItemGroup>
          </Project>
          "@
          Set-Content -Path "${{ matrix.package_id }}.csproj" -Value $projectFileContent
          dotnet pack -c Release -o ../nupkg
          Set-Location -Path ..

      - name: Prepare package structure (CPU) (No Windows)
        if: matrix.type == 'cpu' && matrix.arch != 'arm64' && runner.os != 'Windows'
        run: |
          mkdir -p package/runtimes/${{ matrix.rid }}/native/${{ matrix.mode }}
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            cp build/librwkv.so package/runtimes/${{ matrix.rid }}/native/${{ matrix.mode }}/
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            cp build/librwkv.dylib package/runtimes/${{ matrix.rid }}/native/${{ matrix.mode }}/
          fi

      - name: Prepare package structure (CPU-arm64 or Other) (No Windows)
        if: (matrix.type != 'cpu' || matrix.arch == 'arm64') && runner.os != 'Windows'
        run: |
          mkdir -p package/runtimes/${{ matrix.rid }}/native
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            cp build/librwkv.so package/runtimes/${{ matrix.rid }}/native/
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            cp build/librwkv.dylib package/runtimes/${{ matrix.rid }}/native/
          fi

      - name: Create .nupkg (No Windows)
        if: runner.os != 'Windows'
        run: |
          dotnet new classlib -n ${{ matrix.package_id }} -o ./${{ matrix.package_id }} --force
          cd ${{ matrix.package_id }}
          rm Class1.cs
          cat > ${{ matrix.package_id }}.csproj << EOF
          <Project Sdk="Microsoft.NET.Sdk">
            <PropertyGroup>
              <TargetFramework>netstandard2.0</TargetFramework>
              <PackageId>${{ matrix.package_id }}</PackageId>
              <Version>${{ env.NUGET_VERSION }}</Version>
              <Authors>xcssa</Authors>
              <PackageTags>rwkv,rwkv.cpp,native</PackageTags>
              <IncludeBuildOutput>false</IncludeBuildOutput>
            </PropertyGroup>
            <ItemGroup>
              <None Include="../package/runtimes/**" 
                    Pack="true" 
                    PackagePath="runtimes/" />
            </ItemGroup>
          </Project>
          EOF
          dotnet pack -c Release -o ../nupkg
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package_id }}
          path: nupkg/*.nupkg

  build_convert_tool:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: |
          dotnet publish -r win-x64 -c Release --sc -o publish -p:PublishSingleFile=true ./RWKVSharp.Convert/RWKVSharp.Convert.csproj
          cd ./publish
          zip -r RWKVSharp.Convert.zip ./
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RWKVSharp.Convert.zip
          path: publish/RWKVSharp.Convert.zip
          
  build_quantize_tool:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: |
          dotnet publish -r win-x64 -c Release --sc -o publish -p:PublishSingleFile=true ./RWKVSharp.Quantize/RWKVSharp.Quantize.csproj
          cd ./publish
          zip -r RWKVSharp.Quantize.zip ./
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RWKVSharp.Quantize.zip
          path: publish/RWKVSharp.Quantize.zip

  build_rwkvsharp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: |
          dotnet publish -c Release --sc ./RWKVSharp.Core/RWKVSharp.Core.csproj
          dotnet publish -c Release --sc ./RWKVSharp/RWKVSharp.csproj
          dotnet pack -c Release -o nupkg ./RWKVSharp.Core/RWKVSharp.Core.csproj
          dotnet pack -c Release -o nupkg ./RWKVSharp/RWKVSharp.csproj

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: RWKVSharp
          path: nupkg/*.nupkg

  create_release:
    if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/main' ) || github.event.inputs.create_release == 'true' }}
    runs-on: ubuntu-latest
    needs:
      - build_native
      - build_convert_tool
      - build_quantize_tool
      - build_rwkvsharp
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.NUGET_VERSION }}
          name: Release v${{ env.NUGET_VERSION }}
          body: |
            RWKVSharp Native Packages
          files: artifacts/**/*

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Push RWKVSharp packages to nuget.org
        run: dotnet nuget push artifacts/**/*.nupkg --source https://www.nuget.org -k ${{ secrets.RWKVSHARP_NUGET_KEY }} --skip-duplicate
